[versions]
agp = "8.3.1"
compilerVersion = "4.14.2"
githubCompiler = "5.0.0-rc01"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.11.0"
materialVersion = "1.12.0"
recyclerview = "1.3.2"
constraintlayout = "2.1.4"
lifecycleLivedataKtx = "2.7.0"
lifecycleViewmodelKtx = "2.7.0"
navigationFragment = "2.7.7"
navigationUi = "2.7.7"
compiler = "3.2.0-alpha11"
activity = "1.8.0"
glide = "5.0.0-rc01"
cameraCore = "1.3.3"
cameraLifecycle = "1.3.3"
cameraView = "1.3.3"
cameraCamera2 = "1.2.2"

[libraries]
compiler-v500rc01 = { module = "com.github.bumptech.glide:compiler", version.ref = "githubCompiler" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "compilerVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
material-v1120 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }
compiler = { group = "androidx.databinding", name = "compiler", version.ref = "compiler" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
camera-core = { group = "androidx.camera", name = "camera-core", version.ref = "cameraCore" }
camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "cameraLifecycle" }
camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "cameraView" }
camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "cameraCamera2" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }

